# Generated by Django 5.0.7 on 2024-07-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='最後修改日期'),
        ),
    ]
