# Generated by Django 5.0.7 on 2024-08-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom_app', '0002_alter_student_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='pudu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('robot_id', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='reeman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('host_name', models.CharField(max_length=20)),
            ],
        ),
    ]
