# Generated by Django 5.0.7 on 2024-08-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom_app', '0003_pudu_reeman'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pudu',
            new_name='pudu_robot',
        ),
        migrations.RenameModel(
            old_name='reeman',
            new_name='reeman_robot',
        ),
    ]
