# Generated by Django 5.0.7 on 2024-08-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom_app', '0004_rename_pudu_pudu_robot_rename_reeman_reeman_robot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pudu_robot',
            old_name='robot_id',
            new_name='robotid',
        ),
    ]
