# Generated by Django 4.2.14 on 2024-08-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom_app", "0005_rename_robot_id_pudu_robot_robotid"),
    ]

    operations = [
        migrations.DeleteModel(name="student",),
        migrations.AddField(
            model_name="pudu_robot",
            name="waitpoint",
            field=models.CharField(default="待機", max_length=15),
        ),
        migrations.AddField(
            model_name="reeman_robot",
            name="waitpoint",
            field=models.CharField(default="待機", max_length=15),
        ),
    ]
