# Generated by Django 4.2.14 on 2024-08-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom_app", "0006_delete_student_pudu_robot_waitpoint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pudu_robot",
            name="chargepoint",
            field=models.CharField(default="充電", max_length=15),
        ),
        migrations.AddField(
            model_name="reeman_robot",
            name="chargepoint",
            field=models.CharField(default="充電", max_length=15),
        ),
    ]
